#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www 
# points to your load-balancer IP (lb-01). Let’s also 
# add other subdomains to make our life easier, and write a Bash 
# script that will display information about subdomains

print_info()
{
   local domain=$1
   local subdomain=$2
   local write_down
   write_down=$(dig +noall +answer "${subdomain}.${domain}" | awk 'NR==1{print $5}')
   echo "The domain ${subdomain} is an A record and points to ${write_down}"
}

if [ -z "$2" ]; then
   for sub in "www" "lb-01" "web-01" "web-02"; do
      print_domain_info "$1" "$sub"
   done
else
   print_domain_info "$1" "$2"
fi
