#!/usr/bin/env bash
"""
In this first task you need to configure web-02 to 
be identical to web-01. Fortunately, you built a 
Bash script during your web server project, and 
they’ll now come in handy to easily configure web-02. 
Remember, always try to automate your work!
"""
apt update
apt install -y nginx

HEADER="add_header X-Served-By \$hostname;"
sed -i "/server {/a $HEADER" /etc/nginx/sites-enabled/default

service nginx restart
