#!/usr/bin/env bash

# Bash script that transfers a file from our client to server

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

# Transfer the file
scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP:~"

# Remotely execute the ls command to verify the transfer
ssh -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$USERNAME@$SERVER_IP" "ls ~/" | grep "some_page.html"
