#!/usr/bin/env bash
# This script changes the Nginx port from 8080 to 80 and restarts the Nginx service

# Use sed to replace port 8080 with port 80 in the Nginx configuration file
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

# Check if sed command was successful
if [ $? -eq 0 ]; then
    # Restart the Nginx service
    sudo service nginx restart
    
    # Check if the Nginx restart was successful
    if [ $? -eq 0 ]; then
        echo "Nginx restarted successfully."
    else
        echo "Failed to restart Nginx." >&2
    fi
else
    echo "Failed to update Nginx configuration." >&2
fi
