#!/usr/bin/env bash
# Fix short and sweet

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo nginx -s reload
sudo systemctl status nginx | grep "active (running)" || echo "nginx is not running"
