#!/usr/bin/env bash
# The init scripts that manage manage_my_process

#!/usr/bin/env bash
#This is a script that manages 'manage_my_process'

if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
    if [ -e /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        kill $pid
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi

elif [ "$1" == "restart" ]; then
    if [ -e /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        kill $pid
        rm /var/run/my_process.pid
    fi
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"

else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
