#!/usr/bin/env bash
# The init script that manages manage_my_process

if [ "$1" == "start" ]; then
    ./manage_my_process &
    if [ $? -eq 0 ]; then
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    else
        echo "Failed to start manage_my_process"
    fi

elif [ "$1" == "stop" ]; then
    if [ -e /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        if ps -p $pid > /dev/null; then
            kill $pid
            rm /var/run/my_process.pid
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running"
        fi
    else
        echo "manage_my_process is not running"
    fi

elif [ "$1" == "restart" ]; then
    $0 stop
    $0 start

else
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi
