#!/usr/bin/env bash
# This script prints "Best School" 10 times, and on the 9th iteration, it also prints "Hi" on a new line.

num_count=1

while [ $num_count -le 10 ]
do
    echo "Best School"
    if [ $num_count -eq 9 ]
    then
        echo "Hi"
    fi
    ((num_count++))
done
