#!/usr/bin/env bash

# This script displays "Best School" 10 times.
# On the 9th iteration, it also displays "Hi" on a new line.

num_count=0

while [ $num_count -lt 10 ]
do
	if [ $num_count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( num_count++ ))
done
