#!/usr/bin/env bash
# This script loops from 1 to 20 times using while and case statement

# Displays "4" and then "bad luck from China" for the 4th loop iteration
# Displays "9" and then "bad luck from Japan" for the 9th loop iteration
# Displays "17" and then "bad luck from Italy" for the 17th loop iteration

num_count=1
while ((num_count <= 20))
do
    echo $num_count
    case $num_count in
                4)
                        echo 'bad luck from China'
                        ;;
                9)
                        echo 'bad luck from Japan'
                        ;;
                17)
                        echo 'bad luck from Italy'
                        ;;
    esac
    ((num_count++))
done
