#!/usr/bin/env bash
# This script that displays the time for 12 hours and 59 minutes.

time=0

while [ $time -le 12 ]
do
  echo "Hour: $time"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( time++ ))
done
