#!/usr/bin/env bash
# This script that gives you information about the school file

school_file="school"
if [ -e "$school_file" ]
then
    echo "$school_file file exists"
    if [ -s "$school_file" ]
	then
		echo "school file is not empty"
    else
		echo "school file is empty"
    fi
    if [ -f "$school_file" ]
	then
		echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
